CREATE TABLE IF NOT EXISTS casbin_rules(
  id SERIAL PRIMARY KEY NOT NULL,
  p_type VARCHAR(32) NOT NULL DEFAULT '',
  v0 VARCHAR(255) NOT NULL DEFAULT '',
  v1 VARCHAR(255) NOT NULL DEFAULT '',
  v2 VARCHAR(255) NOT NULL DEFAULT '',
  v3 VARCHAR(255) NOT NULL DEFAULT '',
  v4 VARCHAR(255) NOT NULL DEFAULT '',
  v5 VARCHAR(255) NOT NULL DEFAULT '',
  reserved BOOLEAN NOT NULL DEFAULT FALSE
)
