// Code generated by protoc-gen-go. DO NOT EDIT.
// source: interface/rpc/v1/protocol/user_service.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc66157126b6d759, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ListUserRequestType struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserRequestType) Reset()         { *m = ListUserRequestType{} }
func (m *ListUserRequestType) String() string { return proto.CompactTextString(m) }
func (*ListUserRequestType) ProtoMessage()    {}
func (*ListUserRequestType) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc66157126b6d759, []int{1}
}

func (m *ListUserRequestType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequestType.Unmarshal(m, b)
}
func (m *ListUserRequestType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequestType.Marshal(b, m, deterministic)
}
func (m *ListUserRequestType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequestType.Merge(m, src)
}
func (m *ListUserRequestType) XXX_Size() int {
	return xxx_messageInfo_ListUserRequestType.Size(m)
}
func (m *ListUserRequestType) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequestType.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequestType proto.InternalMessageInfo

type ListUserResponseType struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUserResponseType) Reset()         { *m = ListUserResponseType{} }
func (m *ListUserResponseType) String() string { return proto.CompactTextString(m) }
func (*ListUserResponseType) ProtoMessage()    {}
func (*ListUserResponseType) Descriptor() ([]byte, []int) {
	return fileDescriptor_bc66157126b6d759, []int{2}
}

func (m *ListUserResponseType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserResponseType.Unmarshal(m, b)
}
func (m *ListUserResponseType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserResponseType.Marshal(b, m, deterministic)
}
func (m *ListUserResponseType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserResponseType.Merge(m, src)
}
func (m *ListUserResponseType) XXX_Size() int {
	return xxx_messageInfo_ListUserResponseType.Size(m)
}
func (m *ListUserResponseType) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserResponseType.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserResponseType proto.InternalMessageInfo

func (m *ListUserResponseType) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "protocol.User")
	proto.RegisterType((*ListUserRequestType)(nil), "protocol.ListUserRequestType")
	proto.RegisterType((*ListUserResponseType)(nil), "protocol.ListUserResponseType")
}

func init() {
	proto.RegisterFile("interface/rpc/v1/protocol/user_service.proto", fileDescriptor_bc66157126b6d759)
}

var fileDescriptor_bc66157126b6d759 = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0xc9, 0xcc, 0x2b, 0x49,
	0x2d, 0x4a, 0x4b, 0x4c, 0x4e, 0xd5, 0x2f, 0x2a, 0x48, 0xd6, 0x2f, 0x33, 0xd4, 0x2f, 0x28, 0xca,
	0x2f, 0xc9, 0x4f, 0xce, 0xcf, 0xd1, 0x2f, 0x2d, 0x4e, 0x2d, 0x8a, 0x2f, 0x4e, 0x2d, 0x2a, 0xcb,
	0x4c, 0x4e, 0xd5, 0x03, 0x8b, 0x0a, 0x71, 0xc0, 0x24, 0x95, 0xb4, 0xb8, 0x58, 0x42, 0x8b, 0x53,
	0x8b, 0x84, 0xf8, 0xb8, 0x98, 0x32, 0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x98, 0x32,
	0x53, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0xc0, 0x22, 0x60, 0xb6, 0x92,
	0x28, 0x97, 0xb0, 0x4f, 0x66, 0x71, 0x09, 0x48, 0x7d, 0x50, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x49,
	0x48, 0x65, 0x41, 0xaa, 0x92, 0x0d, 0x97, 0x08, 0x42, 0xb8, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x15,
	0x24, 0x2e, 0xa4, 0xc2, 0xc5, 0x0a, 0xb2, 0xba, 0x58, 0x82, 0x51, 0x81, 0x59, 0x83, 0xdb, 0x88,
	0x4f, 0x0f, 0x66, 0xa9, 0x1e, 0x58, 0x29, 0x44, 0xd2, 0x28, 0x8a, 0x8b, 0x1b, 0xc4, 0x0d, 0x86,
	0xb8, 0x4f, 0xc8, 0x9b, 0x8b, 0x03, 0x66, 0x98, 0x90, 0x2c, 0x42, 0x07, 0x16, 0x7b, 0xa5, 0xe4,
	0xb0, 0x49, 0x23, 0xec, 0x57, 0x62, 0x48, 0x62, 0x03, 0x2b, 0x30, 0x06, 0x04, 0x00, 0x00, 0xff,
	0xff, 0x18, 0x07, 0x3e, 0xf0, 0x1d, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUser(ctx context.Context, in *ListUserRequestType, opts ...grpc.CallOption) (*ListUserResponseType, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUser(ctx context.Context, in *ListUserRequestType, opts ...grpc.CallOption) (*ListUserResponseType, error) {
	out := new(ListUserResponseType)
	err := c.cc.Invoke(ctx, "/protocol.UserService/ListUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUser(context.Context, *ListUserRequestType) (*ListUserResponseType, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) ListUser(ctx context.Context, req *ListUserRequestType) (*ListUserResponseType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListUser not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequestType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protocol.UserService/ListUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUser(ctx, req.(*ListUserRequestType))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUser",
			Handler:    _UserService_ListUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "interface/rpc/v1/protocol/user_service.proto",
}
